### ISSUE TITLE
Unrecognized query argument specified: 'deltaLink'

### ISSUE THREAD

**Issue by NevRA** [Azure-Samples/active-directory-dotnet-graphapi-diffquery#2]
App doesn't work. 

Accessing by https://graph.windows.net returns: 
Directory_BindingRedirection "Tenant information is not available locally. Use the following Urls to get the information."
Accessing by provided in response urls (for example https://directory-s1-sn2.directory.windows.net) returns:
Unrecognized query argument specified: 'deltaLink'.

My url:
https://directory-s1-sn2.directory.windows.net/nuuksio.onmicrosoft.com/directoryObjects?api-version=1.5&deltaLink=

Same problem with default app settings.

**Comment by jmprieur** [comment]
Archived this sample and redirected to a newer version using the Microsoft Graph
