### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by urig** [Azure-Samples/active-directory-dotnet-graphapi-diffquery#3]
The link  http://msdn.microsoft.com/aad in the README.md file is broken. 

When clicking the link, the MSDN website says:

> **We're sorry, the page you requested cannot be found.**
> The URL might be misspelled, or the page you're looking for is no longer available.

**Comment by jmprieur** [comment]
Archived this sample and redirected to a newer version using the Microsoft Graph
